# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
      
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          images_dir: docs/images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs

release:
    name: Create Release with Docs
    runs-on: ubuntu-latest
    needs: converttopdf # Depends on the successful completion of the `converttopdf` job
    steps:
      - name: Generate random tag name
        id: generate_tag
        run: |
          TAG_NAME=$(uuidgen)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
      
      - name: Download docs artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: ./release_docs
      
      - name: List downloaded files
        run: ls -R ./release_docs
      
      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_docs
          asset_name: docs.zip
          asset_content_type: application/zip